[package]
name = "reader-storage-postgres"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
reader-wiki = { path = "../reader-wiki" }
async-trait.workspace = true
chrono.workspace = true
futures-util = "0.3"
murmur3.workspace = true
reader-application = { path = "../reader-application" }
reader-ai = { path = "../reader-ai" }
reader-runtime = { path = "../reader-runtime" }
reader-glossary = { path = "../reader-glossary" }
reader-core = { path = "../reader-core" }
reader-ingest = { path = "../reader-ingest" }
serde.workspace = true
serde_json.workspace = true
sqlx.workspace = true
log.workspace = true
thiserror.workspace = true
tokio.workspace = true
url.workspace = true
uuid.workspace = true

[dev-dependencies]
testcontainers = "0.25"
testcontainers-modules = { version = "0.13", features = ["postgres"] }
reader-server = { path = "../reader-server" }
reader-server-contracts = { path = "../reader-server-contracts" }
reader-server-ui = { path = "../reader-server-ui" }
axum.workspace = true
