import { useState } from "preact/hooks";
import type { Article } from "./data";
import { Icon, type IconName } from "../ui/Icon";
import { formatArticleDate } from "../ui/formatArticleDate";
import "../ai/deepseek.css";

export function ArticleReader({ article, pending, className, onBack, onUpdate, onRefresh, onNotice, onSummarize, summaryPending }: { article: Article; pending:Set<string>;className: string; onBack: () => void; onUpdate: (p: Partial<Article>) => void; onRefresh: () => Promise<void>; onNotice: (m: string) => void; onSummarize: () => void; summaryPending: boolean }) {
  const [refreshing,setRefreshing]=useState(false);
  return <article class={`article-reader ${className}`} aria-label="Article reader"><header class="reader-toolbar"><button class="icon-button reader-back" aria-label="Back to articles" onClick={onBack}><span aria-hidden="true">←</span></button><div class="reader-toolbar__states"><StateButton icon="unread" label={article.read ? "Mark unread" : "Mark read"} active={!article.read} pending={pending.has(`${article.id}:read`)} onClick={() => onUpdate({ read: !article.read })}/><StateButton icon="later" label={article.later ? "Remove from later" : "Read later"} active={article.later} pending={pending.has(`${article.id}:later`)} onClick={() => onUpdate({ later: !article.later })}/><button class="summarize-button" disabled={summaryPending} aria-busy={summaryPending} onClick={onSummarize}>{summaryPending ? <span class="spinner"/> : <Icon name="chat" size={16}/>}Summarize</button></div><a class="icon-button toolbar-tooltip toolbar-tooltip--right" data-tooltip="Open original" aria-label="Open original" href={article.url} target="_blank" rel="noopener noreferrer"><Icon name="external"/></a></header><div class="reader-body"><div class="reader-meta"><span class="source__mark">{article.source.slice(0,1)}</span><div><strong>{article.source}</strong><time>{formatArticleDate(article.age)}</time></div></div><h1>{article.title}</h1><p class="reader-deck">{article.excerpt}</p>{article.fullText === "pending" && <div class="content-status"><span class="spinner"/> Fetching the full article. You can keep reading this excerpt.</div>}{article.fullText === "failed" && <div class="content-status content-status--error"><span>!</span> Full text was unavailable{article.fullTextReason ? ` (${article.fullTextReason})` : ""}. The source excerpt is preserved. <button disabled={refreshing} onClick={() => {if(refreshing)return;setRefreshing(true);onRefresh().then(()=>onNotice("Full-text refresh queued")).catch((error:Error)=>onNotice(error.message)).finally(()=>setRefreshing(false));}}>{refreshing?"Queuing…":"Try again"}</button></div>}{article.fullText === "pending" && <div class="article-content-loading" role="status" aria-label="Loading full article content"><span class="spinner" aria-hidden="true"/></div>}{article.bodyHtml ? <div class="article-content" dangerouslySetInnerHTML={{ __html: article.bodyHtml }}/> : article.body.map((paragraph,index) => <p key={index}>{paragraph}</p>)}<footer class="article-sources"><span>Delivered by</span>{(article.sources ?? [article.source]).map((source) => <span class="source-chip" key={source}>{source}</span>)}</footer></div></article>;
}


function StateButton({ icon, label, active, pending, onClick }: { icon: IconName; label: string; active?: boolean; pending:boolean;onClick: () => void }) { return <button class={`icon-button toolbar-tooltip ${active ? "active" : ""}`} data-tooltip={label} disabled={pending} aria-busy={pending} aria-label={label} aria-pressed={active} onClick={onClick}>{pending?<span class="spinner"/>:<Icon name={icon}/>}</button>; }
