import { fireEvent,render,screen,waitFor,within } from "@testing-library/preact";
import userEvent from "@testing-library/user-event";
import { ApiClient,type SubscriptionDetail,type Transport } from "../api/client";
import type { Subscription } from "./data";
import { SubscriptionsPage } from "./SubscriptionsPage";


const subscriptions:Subscription[]=[
 {id:"one",name:"Alpha feed",sourceTitle:"Alpha",sourceUrl:"https://alpha.test/feed",sourceType:"feed",personalNote:"databases",count:4,status:"active",lastUpdate:"2026-09-25"},
 {id:"two",name:"Broken page",sourceUrl:"https://broken.test",sourceType:"web",count:0,status:"active",needsAttention:true,attentionReason:"Preview no longer finds articles",error:"Selector matched nothing"},
 {id:"old",name:"Archived source",sourceType:"feed",count:0,status:"archived"},
];
const detail:SubscriptionDetail={...subscriptions[0],feedUrls:["https://alpha.test/feed"],extractionSummary:"RSS entries",activity:[],rules:[]};

function client(detailValue:SubscriptionDetail=detail){
 const calls:{path:string;init?:RequestInit}[]=[];
 const transport:Transport=async<T,>(path:string,init?:RequestInit)=>{calls.push({path,init});if(path==="/api/subscriptions/one/extraction")return {sourceType:"feed",feedUrls:["https://canonical.test/rss"],recipeSummary:"Parsed feed entries",lastPreview:"2026-09-25T18:00:00Z"} as T;if(path==="/api/rules?workspace_id=ws")return [{id:"rule",subscriptionId:"one",field:"title",phrase:"Rust",action:"mark_read",enabled:true},{id:"other",subscriptionId:"two",field:"title",phrase:"Other",action:"mark_read",enabled:true}] as T;if(path==="/api/subscriptions/one/activity")return [{id:"event",occurredAt:"2026-09-25T18:00:00Z",successful:false,durationMs:420,discoveredItems:0,diagnostic:"Timed out"}] as T;if(path==="/api/subscriptions/one/source-url/preview")return {token:"preview-token",url:JSON.parse(String(init?.body)).url,title:"Alpha replacement",expiresAt:"2026-09-25T19:00:00Z"} as T;if(path==="/api/subscriptions/one/source-url")return {...detailValue,sourceUrl:"https://new.test/feed"} as T;if(path==="/api/subscriptions/one"&&init?.method==="PATCH")return {...detailValue,name:"Custom Alpha",customName:"Custom Alpha"} as T;if(path==="/api/web-feeds/recipes/one")return {subscriptionId:"one",version:2,draft:{}} as T;if(path==="/api/subscriptions/one")return detailValue as T;if(path==="/api/subscriptions/one/note")return {...detailValue,personalNote:JSON.parse(String(init?.body)).note} as T;return undefined as T};
 return {api:new ApiClient(transport),calls};
}
const props=(api:ApiClient,subscriptionId?:string)=>({client:api,workspaceId:"ws",workspaceName:"Personal",subscriptions,articles:[],subscriptionId,onBack:vi.fn(),onOpenArticles:vi.fn(),onRefresh:vi.fn(async()=>undefined),onPause:vi.fn()});

describe("subscription catalog",()=>{
 it("filters the independent catalog and exposes a textual attention reason",async()=>{const {api}=client();const user=userEvent.setup();render(<SubscriptionsPage {...props(api)}/>);expect(screen.getByText("Alpha feed")).toBeVisible();expect(screen.queryByText("Archived source")).not.toBeInTheDocument();await user.click(screen.getByRole("button",{name:"Needs attention"}));expect(screen.getByText("Broken page")).toBeVisible();expect(screen.getByText("Preview no longer finds articles")).toBeVisible();await user.type(screen.getByRole("searchbox",{name:"Search subscriptions"}),"missing");expect(screen.getByText("No subscriptions in this view")).toBeVisible()});
 it("does not treat a recent raw error as Needs attention without server qualification",async()=>{const {api}=client();const user=userEvent.setup();const recent={id:"recent",name:"Recent transient error",sourceType:"feed" as const,count:0,status:"active" as const,error:"Temporary timeout",needsAttention:false};render(<SubscriptionsPage {...props(api)} subscriptions={[...subscriptions,recent]}/>);await user.click(screen.getByRole("button",{name:"Needs attention"}));expect(screen.queryByText("Recent transient error")).not.toBeInTheDocument();expect(screen.getByText("Broken page")).toBeVisible()});
 it("applies column choices only after confirmation and persists them per workspace",async()=>{const {api}=client();const user=userEvent.setup();const first=render(<SubscriptionsPage {...props(api)}/>);expect(screen.queryByRole("columnheader",{name:"URL"})).not.toBeInTheDocument();await user.click(screen.getByRole("button",{name:"Columns"}));await user.click(within(screen.getByRole("dialog",{name:"Choose table columns"})).getByLabelText("URL"));expect(screen.queryByRole("columnheader",{name:"URL"})).not.toBeInTheDocument();await user.click(screen.getByRole("button",{name:"Apply columns"}));expect(screen.getByRole("columnheader",{name:"URL"})).toBeVisible();first.unmount();render(<SubscriptionsPage {...props(api)}/>);expect(screen.getByRole("columnheader",{name:"URL"})).toBeVisible()});
 it("persists column ordering and widths for the workspace",async()=>{const {api}=client();const user=userEvent.setup();render(<SubscriptionsPage {...props(api)}/>);await user.click(screen.getByRole("button",{name:"Columns"}));await user.click(screen.getByRole("button",{name:"Move Type up"}));await user.selectOptions(screen.getByLabelText("Name width"),"320");await user.click(screen.getByRole("button",{name:"Apply columns"}));const headers=screen.getAllByRole("columnheader").map(x=>x.textContent);expect(headers.indexOf("Type")).toBeLessThan(headers.indexOf("Name"));const nameIndex=headers.indexOf("Name");expect(document.querySelector("colgroup")?.children[nameIndex]).toHaveStyle({width:"320px"})});
 it("persists sorting independently for the workspace",async()=>{const {api}=client();const user=userEvent.setup();const first=render(<SubscriptionsPage {...props(api)}/>);await user.selectOptions(screen.getByLabelText("Sort subscriptions"),"updated");first.unmount();render(<SubscriptionsPage {...props(api)}/>);expect(screen.getByLabelText("Sort subscriptions")).toHaveValue("updated")});
 it("keeps per-row results when a bulk refresh partially fails",async()=>{const {api}=client();const user=userEvent.setup();render(<SubscriptionsPage {...props(api)} onRefresh={vi.fn(async id=>{if(id==="two")throw new Error("Source unavailable")})}/>);await user.click(screen.getByLabelText("Select Alpha feed"));await user.click(screen.getByLabelText("Select Broken page"));await user.click(screen.getByRole("button",{name:"Refresh"}));expect(await screen.findByText("Refresh queued")).toBeVisible();expect(screen.getByText("Source unavailable")).toBeVisible()});
 it("keeps labels in each row for the mobile list layout",()=>{const {api}=client();render(<SubscriptionsPage {...props(api)}/>);const row=screen.getByText("Alpha feed").closest("tr")!;expect(within(row).getByText("active",{selector:"span"})).toBeVisible();expect(row.querySelector('[data-label="Status"]')).not.toBeNull();expect(row.querySelector('[data-label="Unread"]')).not.toBeNull()});
 it("requires one bulk pause reason, updates status and deduplicates activation",async()=>{const {api,calls}=client();const changed=vi.fn();const user=userEvent.setup();render(<SubscriptionsPage {...props(api)} onChanged={changed}/>);await user.click(screen.getByLabelText("Select Alpha feed"));await user.click(screen.getByRole("button",{name:"Pause"}));const submit=screen.getByRole("button",{name:"Pause subscriptions"});expect(submit).toBeDisabled();await user.type(screen.getByLabelText(/Reason/),"Reviewing this source");await user.dblClick(submit);await waitFor(()=>expect(calls.filter(c=>c.path==="/api/subscriptions/one/pause")).toHaveLength(1));expect(JSON.parse(String(calls.find(c=>c.path.endsWith("/pause"))?.init?.body))).toEqual({reason:"Reviewing this source"});expect(changed).toHaveBeenCalledWith(expect.objectContaining({id:"one",status:"paused",reason:"Reviewing this source"}))});
});

describe("subscription details",()=>{
 it("resets every detail view when navigating directly between subscription IDs",async()=>{const {api}=client();const user=userEvent.setup();const view=render(<SubscriptionsPage {...props(api,"one")}/>);await user.click(await screen.findByRole("button",{name:"Update log"}));expect(await screen.findByText("Timed out")).toBeVisible();view.rerender(<SubscriptionsPage {...props(api,"two")}/>);expect(await screen.findByRole("heading",{name:"Broken page",level:1})).toBeVisible();expect(screen.getByRole("button",{name:"Overview"})).toHaveClass("active");expect(screen.queryByText("Timed out")).not.toBeInTheDocument()});
 it("keeps note edits local until explicit save and prevents duplicate activation",async()=>{const {api,calls}=client();const user=userEvent.setup();render(<SubscriptionsPage {...props(api,"one")}/>);const note=await screen.findByRole("textbox",{name:"Personal note"});await user.clear(note);await user.type(note,"private note");expect(screen.getByText("Unsaved changes")).toBeVisible();expect(calls.filter(c=>c.path.endsWith("/note"))).toHaveLength(0);await user.dblClick(screen.getByRole("button",{name:"Save note"}));await waitFor(()=>expect(calls.filter(c=>c.path.endsWith("/note"))).toHaveLength(1));expect(JSON.parse(String(calls.find(c=>c.path.endsWith("/note"))?.init?.body))).toEqual({note:"private note"});expect(screen.getByText("All changes saved")).toBeVisible()});
 it("registers a reload guard only while the note is dirty",async()=>{const {api}=client();const user=userEvent.setup();render(<SubscriptionsPage {...props(api,"one")}/>);const clean=new Event("beforeunload",{cancelable:true});window.dispatchEvent(clean);expect(clean.defaultPrevented).toBe(false);await user.type(await screen.findByRole("textbox",{name:"Personal note"})," changed");const dirty=new Event("beforeunload",{cancelable:true});window.dispatchEvent(dirty);expect(dirty.defaultPrevented).toBe(true)});
 it("reports dirty note state to the global navigation guard",async()=>{const {api}=client();const changed=vi.fn();const user=userEvent.setup();const view=render(<SubscriptionsPage {...props(api,"one")} onDirtyNoteChange={changed}/>);await user.type(await screen.findByRole("textbox",{name:"Personal note"})," changed");expect(changed).toHaveBeenLastCalledWith(true);view.unmount();expect(changed).toHaveBeenLastCalledWith(false)});
 it("restores an archived subscription from its detail page",async()=>{const archived={...detail,id:"old",name:"Archived source",status:"archived" as const};const calls:string[]=[];const api=new ApiClient(async<T,>(path:string,init?:RequestInit)=>{calls.push(`${init?.method??"GET"} ${path}`);if(path==="/api/subscriptions/old/restore")return {...archived,status:"active"} as T;if(path==="/api/subscriptions/old")return archived as T;return undefined as T});const changed=vi.fn();const user=userEvent.setup();render(<SubscriptionsPage {...props(api,"old")} subscriptions={[archived]} onChanged={changed}/>);await user.click(await screen.findByRole("button",{name:"Restore subscription"}));await waitFor(()=>expect(calls).toContain("POST /api/subscriptions/old/restore"));expect(changed).toHaveBeenCalledWith(expect.objectContaining({status:"active"}))});
 it("hides direct URL changes for Web Feed recipes",async()=>{const web={...detail,sourceType:"web" as const,editableWebFeed:true};const {api}=client(web);render(<SubscriptionsPage {...props(api,"one")} subscriptions={[web]}/>);await screen.findByRole("heading",{name:"Alpha feed"});expect(screen.queryByRole("button",{name:"Change source URL"})).not.toBeInTheDocument()});
 it("loads exact extraction projections from the API",async()=>{const {api,calls}=client();const user=userEvent.setup();render(<SubscriptionsPage {...props(api,"one")}/>);await user.click(await screen.findByRole("button",{name:"Extraction"}));expect(await screen.findByText("https://canonical.test/rss")).toBeVisible();expect(screen.getByText("Parsed feed entries")).toBeVisible();expect(calls.some(c=>c.path.endsWith("/extraction"))).toBe(true)});
 it("loads and scopes real rules from the workspace API",async()=>{const {api,calls}=client();const user=userEvent.setup();render(<SubscriptionsPage {...props(api,"one")}/>);await user.click(await screen.findByRole("button",{name:"Rules"}));expect(await screen.findByText(/title contains “Rust”/)).toBeVisible();expect(screen.queryByText(/Other/)).not.toBeInTheDocument();expect(screen.getByText("Workspace-level rules are not supported yet.")).toBeVisible();expect(calls.some(c=>c.path==="/api/rules?workspace_id=ws")).toBe(true)});
 it("opens the retained failure log directly",async()=>{const {api,calls}=client();render(<SubscriptionsPage {...props(api,"one")} initialTab="activity"/>);expect(await screen.findByText("Timed out")).toBeVisible();expect(screen.getByRole("button",{name:"Update log"})).toHaveClass("active");expect(calls.filter(c=>c.path.endsWith("/activity"))).toHaveLength(1)});
 it("loads the 30-day activity stream when its tab opens",async()=>{const {api,calls}=client();const user=userEvent.setup();render(<SubscriptionsPage {...props(api,"one")}/>);await user.click(await screen.findByRole("button",{name:"Update log"}));expect(await screen.findByText("Timed out")).toBeVisible();expect(screen.getByText("420 ms · 0 items")).toBeVisible();expect(calls.filter(c=>c.path.endsWith("/activity"))).toHaveLength(1)});
 it("previews a replacement URL before committing it",async()=>{const {api,calls}=client();const user=userEvent.setup();render(<SubscriptionsPage {...props(api,"one")}/>);await user.click(await screen.findByRole("button",{name:"Change source URL"}));const field=screen.getByRole("textbox",{name:"New source URL"});await user.clear(field);await user.type(field,"https://new.test/feed");await user.click(screen.getByRole("button",{name:"Preview source"}));expect(await screen.findByText("Alpha replacement")).toBeVisible();expect(calls.some(c=>c.path.endsWith("/source-url/preview")&&c.init?.method==="POST")).toBe(true);await user.click(screen.getByRole("button",{name:"Confirm change"}));await waitFor(()=>expect(calls.some(c=>c.path.endsWith("/source-url")&&c.init?.method==="PUT"&&JSON.parse(String(c.init.body)).previewToken==="preview-token")).toBe(true))});
 it("edits the custom name through PATCH",async()=>{const {api,calls}=client();const user=userEvent.setup();render(<SubscriptionsPage {...props(api,"one")}/>);await user.click(await screen.findByRole("button",{name:"Edit name"}));const field=screen.getByRole("textbox",{name:"Custom name"});await user.clear(field);await user.type(field,"Custom Alpha");await user.click(screen.getByRole("button",{name:"Save name"}));await waitFor(()=>expect(calls.some(c=>c.path==="/api/subscriptions/one"&&c.init?.method==="PATCH")).toBe(true));expect(await screen.findByRole("heading",{name:"Custom Alpha",level:1})).toBeVisible()});
 it("opens the existing Web Feed editor for editable sources",async()=>{const editable={...detail,editableWebFeed:true};const {api}=client(editable);const onEditRecipe=vi.fn();render(<SubscriptionsPage {...props(api,"one")} subscriptions={[editable]} onEditRecipe={onEditRecipe}/>);const user=userEvent.setup();await user.click(await screen.findByRole("button",{name:"Extraction"}));await user.click(await screen.findByRole("button",{name:"Edit extraction recipe"}));await waitFor(()=>expect(onEditRecipe).toHaveBeenCalledWith(expect.objectContaining({subscriptionId:"one",version:2})))});
});
