import { useEffect, useMemo, useRef, useState } from "preact/hooks";
import type { Article, Subscription } from "./data";
import type { ApiClient, RuleDraft, SourceUrlPreview, SubscriptionActivity, SubscriptionDetail, SubscriptionExtraction, WebFeedRecipeView } from "../api/client";
import { AutofillResistantField, AutofillResistantSelect, AutofillResistantTextarea } from "../ui/fields";
import { Icon } from "../ui/Icon";
import { Dialog } from "./Dialog";

type CatalogView="current"|"attention"|"archived";
type Sort="name"|"updated"|"unread";
type DetailTab="overview"|"extraction"|"rules"|"activity";
type Column="name"|"kind"|"status"|"updated"|"unread"|"url"|"note"|"interval"|"error"|"added";
const defaults:Column[]=["name","kind","status","updated","unread"];
const labels:Record<Column,string>={name:"Name",kind:"Type",status:"Status",updated:"Last updated",unread:"Unread",url:"URL",note:"Personal note",interval:"Update frequency",error:"Current error",added:"Added"};
const memoryLayouts=new Map<string,string>();
type Layout={columns:Column[];widths:Partial<Record<Column,number>>};
const defaultWidths:Record<Column,number>={name:220,kind:110,status:110,updated:160,unread:85,url:280,note:240,interval:150,error:240,added:160};

export function SubscriptionsPage({client,workspaceId,workspaceName,subscriptions,articles,subscriptionId,initialTab,onBack,onOpenDetail,onOpenArticles,onRefresh,onPause,onChanged,onEditRecipe,onDirtyNoteChange}:{client:ApiClient;workspaceId:string;workspaceName:string;subscriptions:Subscription[];articles:Article[];subscriptionId?:string;initialTab?:DetailTab;onBack:()=>void;onOpenDetail?:(id:string)=>void;onOpenArticles:(id:string)=>void;onRefresh:(id:string)=>Promise<void>;onPause:(id:string)=>void;onChanged?:(item:Subscription)=>void;onEditRecipe?:(recipe:WebFeedRecipeView)=>void;onDirtyNoteChange?:(dirty:boolean)=>void}){
 if(subscriptionId)return <SubscriptionDetails key={`${subscriptionId}:${initialTab??"overview"}`} {...{client,workspaceId,workspaceName,subscriptions,articles,subscriptionId,initialTab,onBack,onOpenArticles,onRefresh,onPause,onChanged,onEditRecipe,onDirtyNoteChange}}/>;
 return <SubscriptionCatalog {...{client,workspaceId,workspaceName,subscriptions,onBack,onRefresh,onPause,onOpenDetail,onChanged}}/>;
}

function SubscriptionCatalog({client,workspaceId,workspaceName,subscriptions,onBack,onRefresh,onPause,onOpenDetail,onChanged}:{client:ApiClient;workspaceId:string;workspaceName:string;subscriptions:Subscription[];onBack:()=>void;onRefresh:(id:string)=>Promise<void>;onPause:(id:string)=>void;onOpenDetail?:(id:string)=>void;onChanged?:(item:Subscription)=>void}){
 const key=`reader.subscription-columns.${workspaceId}`;
 const initial=readLayout(key);
 const sortKey=`reader.subscription-sort.${workspaceId}`;
 const [view,setView]=useState<CatalogView>("current"),[query,setQuery]=useState(""),[status,setStatus]=useState("all"),[kind,setKind]=useState("all"),[sort,setSort]=useState<Sort>(()=>readSort(sortKey)),[selected,setSelected]=useState<Set<string>>(()=>new Set()),[pending,setPending]=useState(false),[results,setResults]=useState<Map<string,string>>(()=>new Map()),[layout,setLayout]=useState<Layout>(initial),[draft,setDraft]=useState<Layout>(initial),[editing,setEditing]=useState(false),[pauseOpen,setPauseOpen]=useState(false),[pauseReason,setPauseReason]=useState(""),[pauseError,setPauseError]=useState("");
 const pendingRef=useRef(false);
 useEffect(()=>{const next=readLayout(key);setLayout(next);setDraft(next);setSort(readSort(sortKey));setSelected(new Set());setResults(new Map())},[key,sortKey]);
 const rows=useMemo(()=>subscriptions.filter(item=>view==="archived"?item.status==="archived":view==="attention"?item.status!=="archived"&&!!(item.needsAttention||item.attentionReason||item.incomplete):item.status!=="archived").filter(item=>status==="all"||item.status===status).filter(item=>kind==="all"||item.sourceType===kind).filter(item=>`${item.name} ${item.sourceUrl??""} ${item.personalNote??""}`.toLocaleLowerCase().includes(query.toLocaleLowerCase())).sort((a,b)=>sort==="name"?a.name.localeCompare(b.name):sort==="unread"?(b.unreadCount??0)-(a.unreadCount??0):String(b.lastUpdate??"").localeCompare(String(a.lastUpdate??""))),[subscriptions,view,status,kind,query,sort]);
 const runBulk=async(ids:string[],work:(id:string)=>Promise<void>,success:string)=>{if(pendingRef.current||!ids.length)return;pendingRef.current=true;setPending(true);setResults(old=>{const next=new Map(old);ids.forEach(id=>next.set(id,"Pending…"));return next});const settled=await Promise.allSettled(ids.map(work));setResults(old=>{const next=new Map(old);settled.forEach((result,index)=>next.set(ids[index],result.status==="fulfilled"?success:result.reason instanceof Error?result.reason.message:"Failed"));return next});window.setTimeout(()=>{pendingRef.current=false;setPending(false)},250)};
 const refresh=()=>runBulk([...selected],onRefresh,"Refresh queued");
 const applyColumns=()=>{setLayout(draft);writeLayout(key,draft);setEditing(false)};
 return <section class="subscriptions-page"><header class="entity-header"><div><button class="text-button" onClick={onBack}>← Back to reader</button><p class="eyebrow">{workspaceName}</p><h1>Subscriptions</h1><p>Browse, inspect and maintain every source in this workspace.</p></div></header>
  <nav class="entity-tabs" aria-label="Subscription views">{(["current","attention","archived"] as const).map(item=><button class={view===item?"active":""} onClick={()=>{setView(item);setSelected(new Set())}}>{item==="attention"?"Needs attention":item[0].toUpperCase()+item.slice(1)}</button>)}</nav>
  <div class="catalog-toolbar"><AutofillResistantField aria-label="Search subscriptions" type="search" placeholder="Search name, URL or personal note" value={query} onInput={e=>setQuery(e.currentTarget.value)}/><AutofillResistantSelect aria-label="Filter by status" value={status} onChange={e=>setStatus(e.currentTarget.value)}><option value="all">All statuses</option><option value="active">Active</option><option value="paused">Paused</option><option value="archived">Archived</option></AutofillResistantSelect><AutofillResistantSelect aria-label="Filter by type" value={kind} onChange={e=>setKind(e.currentTarget.value)}><option value="all">All types</option><option value="feed">Feed</option><option value="web">Web feed</option><option value="built_in">Built in</option></AutofillResistantSelect><AutofillResistantSelect aria-label="Sort subscriptions" value={sort} onChange={e=>{const next=e.currentTarget.value as Sort;setSort(next);writeSort(sortKey,next)}}><option value="name">Name</option><option value="updated">Last updated</option><option value="unread">Unread</option></AutofillResistantSelect><button class="secondary-button" onClick={()=>{setDraft(layout);setEditing(true)}}>Columns</button></div>
  <div class="bulk-bar" aria-live="polite"><span>{selected.size?`${selected.size} selected`: `${rows.length} subscriptions`}</span><button disabled={!selected.size||pending} aria-busy={pending} onClick={refresh}>{pending?<><span class="spinner"/>Refreshing…</>:"Refresh"}</button><button disabled={!selected.size||pending} onClick={()=>setPauseOpen(true)}>Pause</button></div>
  <div class="subscription-table-wrap"><table class="subscription-table"><colgroup><col style="width:42px"/>{layout.columns.map(c=><col style={`width:${layout.widths[c]??defaultWidths[c]}px`}/>)}<col style="width:110px"/></colgroup><thead><tr><th><AutofillResistantField type="checkbox" aria-label="Select all visible subscriptions" checked={!!rows.length&&rows.every(r=>selected.has(r.id))} onChange={e=>setSelected(e.currentTarget.checked?new Set(rows.map(r=>r.id)):new Set())}/></th>{layout.columns.map(c=><th>{labels[c]}</th>)}<th aria-label="Actions"/></tr></thead><tbody>{rows.map(item=><tr><td><AutofillResistantField type="checkbox" aria-label={`Select ${item.name}`} checked={selected.has(item.id)} onChange={()=>setSelected(old=>toggle(old,item.id))}/></td>{layout.columns.map(c=><td data-label={labels[c]}>{cell(item,c,onOpenDetail)}{c==="name"&&results.has(item.id)&&<small class={`bulk-result ${results.get(item.id)==="Pending…"?"pending":(results.get(item.id)?.includes("queued")||results.get(item.id)==="Paused")?"success":"error"}`}>{results.get(item.id)}</small>}</td>)}<td class="row-link"><a href={`/subscriptions/${encodeURIComponent(item.id)}`} onClick={e=>{if(onOpenDetail){e.preventDefault();onOpenDetail(item.id)}}}>View details</a></td></tr>)}</tbody></table>{!rows.length&&<div class="catalog-empty"><Icon name="feed"/><strong>No subscriptions in this view</strong><span>Try another filter or search term.</span></div>}</div>
  {editing&&<div class="column-drawer" role="dialog" aria-label="Choose table columns"><h2>Table columns</h2><p>Choose, order and size fields. Changes apply when you confirm.</p>{(Object.keys(labels) as Column[]).map(c=>{const shown=draft.columns.includes(c),index=draft.columns.indexOf(c);return <div class="column-option"><label><AutofillResistantField type="checkbox" disabled={c==="name"} checked={shown} onChange={()=>setDraft(old=>({...old,columns:shown?old.columns.filter(x=>x!==c):[...old.columns,c]}))}/>{labels[c]}</label>{shown&&<><div class="column-order"><button aria-label={`Move ${labels[c]} up`} disabled={index<1} onClick={()=>setDraft(old=>({...old,columns:move(old.columns,index,index-1)}))}>↑</button><button aria-label={`Move ${labels[c]} down`} disabled={index===draft.columns.length-1} onClick={()=>setDraft(old=>({...old,columns:move(old.columns,index,index+1)}))}>↓</button></div><AutofillResistantSelect aria-label={`${labels[c]} width`} value={String(draft.widths[c]??defaultWidths[c])} onChange={e=>setDraft(old=>({...old,widths:{...old.widths,[c]:Number(e.currentTarget.value)}}))}><option value={Math.max(80,defaultWidths[c]-60)}>Narrow</option><option value={defaultWidths[c]}>Default</option><option value={defaultWidths[c]+100}>Wide</option></AutofillResistantSelect></>}</div>})}<footer><button class="secondary-button" onClick={()=>setEditing(false)}>Cancel</button><button class="primary-button" onClick={applyColumns}>Apply columns</button></footer></div>}
  {pauseOpen&&<Dialog title="Pause selected subscriptions" description="One required reason will be recorded for every selected subscription." onClose={()=>{if(!pending)setPauseOpen(false)}}><div class="modal__body"><label>Reason <span class="required">Required</span><AutofillResistantTextarea rows={4} value={pauseReason} onInput={e=>setPauseReason(e.currentTarget.value)} autoFocus/></label><span class="field-help field-help--error" role="alert">{pauseError}</span></div><footer class="modal__actions"><span/><span/><button class="secondary-button" disabled={pending} onClick={()=>setPauseOpen(false)}>Cancel</button><button class="danger-button" disabled={pending||!pauseReason.trim()} aria-busy={pending} onClick={()=>{if(pending||!pauseReason.trim())return;setPauseError("");runBulk([...selected],async id=>{await client.pauseSubscription(id,pauseReason);const current=subscriptions.find(item=>item.id===id);if(current)onChanged?.({...current,status:"paused",reason:pauseReason,reasonAt:new Date().toISOString()})},"Paused").then(()=>{setPauseOpen(false);setSelected(new Set());setPauseReason("")}).catch((e:Error)=>setPauseError(e.message))}}>{pending?<><span class="spinner"/>Pausing…</>:"Pause subscriptions"}</button></footer></Dialog>}
 </section>;
}

function SubscriptionDetails({client,workspaceId,workspaceName,subscriptions,articles,subscriptionId,initialTab,onBack,onOpenArticles,onRefresh,onPause,onChanged,onEditRecipe,onDirtyNoteChange}:{client:ApiClient;workspaceId:string;workspaceName:string;subscriptions:Subscription[];articles:Article[];subscriptionId:string;initialTab?:DetailTab;onBack:()=>void;onOpenArticles:(id:string)=>void;onRefresh:(id:string)=>Promise<void>;onPause:(id:string)=>void;onChanged?:(item:Subscription)=>void;onEditRecipe?:(recipe:WebFeedRecipeView)=>void;onDirtyNoteChange?:(dirty:boolean)=>void}){
 const summary=subscriptions.find(x=>x.id===subscriptionId);const [detail,setDetail]=useState<SubscriptionDetail|null>(summary??null),[tab,setTab]=useState(initialTab??"overview"),[note,setNote]=useState(summary?.personalNote??""),[savedNote,setSavedNote]=useState(summary?.personalNote??""),[saving,setSaving]=useState(false),[refreshing,setRefreshing]=useState(false),[restoring,setRestoring]=useState(false),[error,setError]=useState(""),[activity,setActivity]=useState<SubscriptionActivity[]|null>(null),[activityLoading,setActivityLoading]=useState(false),[extraction,setExtraction]=useState<SubscriptionExtraction|null>(null),[extractionLoading,setExtractionLoading]=useState(false),[extractionAttempted,setExtractionAttempted]=useState(false),[rules,setRules]=useState<RuleDraft[]|null>(null),[rulesLoading,setRulesLoading]=useState(false),[nameEditing,setNameEditing]=useState(false),[customName,setCustomName]=useState(summary?.customName??""),[urlOpen,setUrlOpen]=useState(false),[newUrl,setNewUrl]=useState(summary?.sourceUrl??""),[urlPreview,setUrlPreview]=useState<SourceUrlPreview|null>(null),[urlPending,setUrlPending]=useState(false);
 const noteEdited=useRef(false);
 const dirty=note!==savedNote;
 useEffect(()=>{let active=true;client.getSubscription(subscriptionId).then(v=>{if(active&&v){setDetail(v);if(!noteEdited.current)setNote(v.personalNote??"");setSavedNote(v.personalNote??"")}}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[client,subscriptionId]);
 useEffect(()=>{const before=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue=""}};window.addEventListener("beforeunload",before);return()=>window.removeEventListener("beforeunload",before)},[dirty]);
 useEffect(()=>{onDirtyNoteChange?.(dirty);return()=>onDirtyNoteChange?.(false)},[dirty,onDirtyNoteChange]);
 useEffect(()=>{if(tab!=="activity"||activity!==null||activityLoading)return;setActivityLoading(true);client.subscriptionActivity(subscriptionId).then(setActivity).catch(e=>{setError(e.message);setActivity([])}).finally(()=>setActivityLoading(false))},[tab,activity,activityLoading,client,subscriptionId]);
 useEffect(()=>{if(tab!=="extraction"||extractionAttempted||extractionLoading)return;setExtractionAttempted(true);setExtractionLoading(true);client.subscriptionExtraction(subscriptionId).then(setExtraction).catch(e=>setError(e.message)).finally(()=>setExtractionLoading(false))},[tab,extractionAttempted,extractionLoading,client,subscriptionId]);
 useEffect(()=>{if(tab!=="rules"||rules!==null||rulesLoading)return;setRulesLoading(true);client.listRules(workspaceId).then(values=>setRules(values.filter(rule=>rule.subscriptionId===subscriptionId))).catch(e=>{setError(e.message);setRules([])}).finally(()=>setRulesLoading(false))},[tab,rules,rulesLoading,client,workspaceId,subscriptionId]);
 const leave=(action:()=>void)=>{if(!dirty||window.confirm("Discard unsaved changes to your personal note?"))action()};
 if(!detail)return <section class="subscriptions-page"><button class="text-button" onClick={onBack}>← Back to subscriptions</button><div class="catalog-empty"><strong>Subscription not found</strong></div></section>;
 const latest=articles.filter(a=>a.subscriptionIds?.includes(subscriptionId)).slice(0,5);
 const save=()=>{if(saving)return;setSaving(true);setError("");client.saveSubscriptionNote(subscriptionId,note).then(v=>{setDetail(v);noteEdited.current=false;setSavedNote(note)}).catch(e=>setError(e.message)).finally(()=>setSaving(false))};
 return <section class="subscriptions-page detail-page"><header class="entity-header"><div><button class="text-button" onClick={onBack}>← Back to subscriptions</button><p class="eyebrow">{workspaceName} · Subscription</p><h1>{detail.name}</h1><p>{detail.sourceTitle&&detail.sourceTitle!==detail.name?`Source title: ${detail.sourceTitle}`:"Source details and collection health"}</p></div><div class="entity-actions">{detail.status==="archived"?<button class="primary-button" disabled={restoring} aria-busy={restoring} onClick={()=>{if(restoring)return;setRestoring(true);client.restoreSubscription(detail.id).then(item=>{setDetail(old=>old?{...old,...item}:old);onChanged?.(item)}).catch(e=>setError(e.message)).finally(()=>setRestoring(false))}}>{restoring?"Restoring…":"Restore subscription"}</button>:<><button class="secondary-button" disabled={refreshing} onClick={()=>{setRefreshing(true);onRefresh(detail.id).finally(()=>setRefreshing(false))}}>{refreshing?"Queuing…":"Refresh"}</button><button class="secondary-button" onClick={()=>onPause(detail.id)}>Pause</button></>}</div></header>
 <nav class="entity-tabs" aria-label="Subscription details">{([["overview","Overview"],["extraction","Extraction"],["rules","Rules"],["activity","Update log"]] satisfies [DetailTab,string][]).map(([id,label])=><button class={tab===id?"active":""} onClick={()=>leave(()=>setTab(id))}>{label}</button>)}</nav>
 {tab==="overview"&&<div class="detail-grid"><section class="detail-card"><div class="card-heading"><h2>Source</h2><button class="text-button" onClick={()=>{setCustomName(detail.customName??"");setNameEditing(true)}}>Edit name</button></div><dl><dt>Custom name</dt><dd>{detail.customName||"Not set"}</dd><dt>Source title</dt><dd>{detail.sourceTitle||detail.name}</dd><dt>URL</dt><dd class="source-url"><span>{detail.sourceUrl||"Not reported"}</span>{detail.sourceUrl&&<><a href={detail.sourceUrl} target="_blank" rel="noreferrer">Open</a><button onClick={()=>navigator.clipboard.writeText(detail.sourceUrl!)}>Copy</button></>}{detail.sourceType!=="web"&&<button onClick={()=>{setNewUrl(detail.sourceUrl??"");setUrlPreview(null);setUrlOpen(true)}}>Change source URL</button>}</dd><dt>Status</dt><dd>{detail.status}{detail.attentionReason&&<small class="attention-reason">{detail.attentionReason}</small>}</dd><dt>Last updated</dt><dd>{detail.lastUpdate?new Date(detail.lastUpdate).toLocaleString():"Not updated yet"}</dd><dt>Articles</dt><dd>{detail.count}</dd><dt>Unread</dt><dd>{detail.unreadCount??0}</dd></dl></section><section class="detail-card note-card"><h2>Personal note</h2><AutofillResistantTextarea aria-label="Personal note" rows={7} value={note} onInput={e=>{noteEdited.current=true;setNote(e.currentTarget.value)}}/><div class="note-status" aria-live="polite"><span>{dirty?"Unsaved changes":"All changes saved"}</span><button class="primary-button" disabled={!dirty||saving} aria-busy={saving} onClick={save}>{saving?<><span class="spinner"/>Saving…</>:"Save note"}</button></div><span class="field-help field-help--error">{error}</span></section><section class="detail-card recent-card"><div class="card-heading"><h2>Latest articles</h2><button class="text-button" onClick={()=>onOpenArticles(detail.id)}>View all articles</button></div>{latest.length?latest.map(a=><article><strong>{a.title}</strong><span>{a.age} ago · {a.read?"Read":"Unread"}</span></article>):<p>No articles collected yet.</p>}</section></div>}
 {tab==="extraction"&&<section class="detail-card detail-single" aria-busy={extractionLoading}><div class="card-heading"><div><h2>Extraction</h2>{extraction?.recipeSummary&&<p>{extraction.recipeSummary}</p>}</div>{detail.editableWebFeed&&<button class="primary-button" onClick={()=>client.getWebFeedRecipe(detail.id).then(recipe=>onEditRecipe?.(recipe)).catch(e=>setError(e.message))}>Edit extraction recipe</button>}</div>{extractionLoading?<p>Loading extraction details…</p>:extraction&&<dl><dt>Source type</dt><dd>{formatKind(extraction.sourceType as Subscription["sourceType"])}</dd><dt>Discovered feed URLs</dt><dd>{extraction.feedUrls.length?extraction.feedUrls.join(", "):"No feed URLs discovered"}</dd>{extraction.recipeVersion!==undefined&&<><dt>Recipe version</dt><dd>{extraction.recipeVersion}</dd></>}<dt>Last preview</dt><dd>{extraction.lastPreview?new Date(extraction.lastPreview).toLocaleString():"No preview recorded"}</dd></dl>}</section>}
 {tab==="rules"&&<section class="detail-card detail-single" aria-busy={rulesLoading}><h2>Rules</h2>{rulesLoading?<p>Loading rules…</p>:<RuleGroup title="Subscription rules" rules={(rules??[]).map(rule=>({id:rule.id??`${rule.field}:${rule.phrase}`,summary:`${rule.field.replaceAll("_"," ")} contains “${rule.phrase}” → ${rule.action.replaceAll("_"," ")}`,enabled:rule.enabled}))}/>}<RuleGroup title="Workspace-level rules" rules={[]} empty="Workspace-level rules are not supported yet."/></section>}
 {tab==="activity"&&<section class="detail-card detail-single"><div class="card-heading"><div><h2>Update log · last 30 days</h2><p>Every recorded fetch attempt for this subscription, including the full failure reason.</p></div></div><div class="activity-list" aria-busy={activityLoading}>{activityLoading?<p>Loading update log…</p>:activity?.length?activity.map(a=><article><span class={`status-pill status-${a.successful?"success":"error"}`}>{a.successful?"Success":"Failed"}</span><strong>{new Date(a.occurredAt).toLocaleString()}</strong><span>{a.durationMs===undefined?"Duration unavailable":`${a.durationMs} ms`} · {a.discoveredItems===undefined?"Items unavailable":`${a.discoveredItems} items`}</span>{a.diagnostic&&<p class="activity-diagnostic">{a.diagnostic}</p>}</article>):<p>No update attempts recorded in the last 30 days.</p>}</div></section>}
 {nameEditing&&<Dialog title="Edit custom name" description="The source title remains available and continues updating from the feed." onClose={()=>!saving&&setNameEditing(false)}><div class="modal__body"><label>Custom name<AutofillResistantField aria-label="Custom name" value={customName} onInput={e=>setCustomName(e.currentTarget.value)}/></label></div><footer class="modal__actions"><span/><span/><button class="secondary-button" disabled={saving} onClick={()=>setNameEditing(false)}>Cancel</button><button class="primary-button" disabled={saving||customName.trim()!==customName} onClick={()=>{setSaving(true);client.renameSubscription(detail.id,customName).then(item=>{setDetail(old=>old?{...old,...item}:old);onChanged?.(item);setNameEditing(false)}).catch(e=>setError(e.message)).finally(()=>setSaving(false))}}>Save name</button></footer></Dialog>}
 {urlOpen&&<Dialog title="Change source URL" description="The current source stays active until you preview and confirm the replacement." onClose={()=>!urlPending&&setUrlOpen(false)}><div class="modal__body source-url-flow"><label>New source URL<AutofillResistantField aria-label="New source URL" type="url" value={newUrl} onInput={e=>{setNewUrl(e.currentTarget.value);setUrlPreview(null)}}/></label>{urlPreview&&<div class="source-preview" aria-live="polite"><span>Preview ready</span><strong>{urlPreview.title}</strong><small>{urlPreview.url}</small></div>}<span class="field-help field-help--error" role="alert">{error}</span></div><footer class="modal__actions"><button class="secondary-button" disabled={urlPending} onClick={()=>setUrlOpen(false)}>Cancel</button><span/><button class="secondary-button" disabled={urlPending||!newUrl||!!urlPreview} aria-busy={urlPending&&!urlPreview} onClick={()=>{setUrlPending(true);setError("");client.previewSubscriptionSourceUrl(detail.id,newUrl).then(setUrlPreview).catch(e=>setError(e.message)).finally(()=>setUrlPending(false))}}>{urlPending&&!urlPreview?"Previewing…":"Preview source"}</button><button class="primary-button" disabled={urlPending||!urlPreview} aria-busy={urlPending&&!!urlPreview} onClick={()=>{if(!urlPreview)return;setUrlPending(true);client.commitSubscriptionSourceUrl(detail.id,urlPreview.token).then(item=>{setDetail(old=>old?{...old,...item}:old);onChanged?.(item);setUrlOpen(false)}).catch(e=>setError(e.message)).finally(()=>setUrlPending(false))}}>{urlPending&&urlPreview?"Changing…":"Confirm change"}</button></footer></Dialog>}
 </section>;
}
function RuleGroup({title,rules,empty="No rules in this group."}:{title:string;rules:{id:string;summary:string;enabled:boolean}[];empty?:string}){return <div class="rule-group"><h3>{title}</h3>{rules.length?rules.map(r=><div><span>{r.summary}</span><small>{r.enabled?"Enabled":"Disabled"}</small></div>):<p>{empty}</p>}</div>}
function readLayout(key:string):Layout{try{const raw=globalThis.localStorage?.getItem(key)??memoryLayouts.get(key)??"";const v=JSON.parse(raw);if(Array.isArray(v)&&v.includes("name"))return {columns:v,widths:{}};if(Array.isArray(v?.columns)&&v.columns.includes("name"))return v}catch{}return {columns:defaults,widths:{}}}
function writeLayout(key:string,value:Layout){const raw=JSON.stringify(value);memoryLayouts.set(key,raw);try{globalThis.localStorage?.setItem(key,raw)}catch{}}
function readSort(key:string):Sort{try{const value=globalThis.localStorage?.getItem(key)??memoryLayouts.get(key);if(value==="name"||value==="updated"||value==="unread")return value}catch{}return "name"}
function writeSort(key:string,value:Sort){memoryLayouts.set(key,value);try{globalThis.localStorage?.setItem(key,value)}catch{}}
function move<T>(values:T[],from:number,to:number){const copy=[...values];const [item]=copy.splice(from,1);copy.splice(to,0,item);return copy}
function toggle(set:Set<string>,id:string){const n=new Set(set);n.has(id)?n.delete(id):n.add(id);return n}
function formatKind(v?:Subscription["sourceType"]){return v?v.replaceAll("_"," ").replace(/^./,x=>x.toUpperCase()):"Unknown"}
function cell(s:Subscription,c:Column,onOpenDetail?:(id:string)=>void){switch(c){case"name":return <a class="entity-name" href={`/subscriptions/${encodeURIComponent(s.id)}`} onClick={e=>{if(onOpenDetail){e.preventDefault();onOpenDetail(s.id)}}}>{s.name}{s.attentionReason&&<small>{s.attentionReason}</small>}</a>;case"kind":return formatKind(s.sourceType);case"status":return <span class={`status-pill status-${s.status}`}>{s.status}</span>;case"updated":return s.lastUpdate||"Never";case"unread":return s.unreadCount??0;case"url":return s.sourceUrl||"—";case"note":return s.personalNote||"—";case"interval":return s.pollingInterval||"—";case"error":return s.error||"—";case"added":return s.createdAt||"—"}}
