#!/usr/bin/env python3
"""Explicit generation only. Unknown schema constructs fail rather than weaken types."""
import argparse, json, pathlib, subprocess
ROOT = pathlib.Path(__file__).resolve().parents[1]

# Closed validator vocabulary. Format is an annotation in JSON Schema 2020-12;
# syntax/identity validation belongs to backend constructors, not JS coercion.
SUPPORTED = {"$schema", "$defs", "$ref", "title", "description", "default", "format",
             "type", "properties", "required", "additionalProperties", "items",
             "minimum", "maximum", "enum", "const", "anyOf", "oneOf", "allOf"}
FORMATS = {"uint", "uint64", "uint32", "int64", "double", "date-time", "uuid"}
def validate_schema(schema):
    if isinstance(schema, bool): return
    unknown = set(schema) - SUPPORTED
    if unknown: raise ValueError("Unsupported runtime schema keywords: " + ", ".join(sorted(unknown)))
    if "format" in schema and schema["format"] not in FORMATS:
        raise ValueError("Unsupported format annotation: " + schema["format"])
    if "$ref" in schema and not schema["$ref"].startswith("#/$defs/"):
        raise ValueError("Only local definitions are supported")
    for key in ("$defs", "properties"):
        for child in schema.get(key, {}).values(): validate_schema(child)
    for key in ("items", "additionalProperties"):
        if key in schema: validate_schema(schema[key])
    for key in ("anyOf", "oneOf", "allOf"):
        for child in schema.get(key, []): validate_schema(child)

def ts(schema):
    if schema is True: return 'unknown'
    if schema is False: return 'never'
    if '$ref' in schema: return schema['$ref'].split('/')[-1]
    if 'const' in schema: return json.dumps(schema['const'])
    if 'enum' in schema: return ' | '.join(json.dumps(v) for v in schema['enum'])
    for key in ('anyOf','oneOf','allOf'):
        if key in schema:
            branches='('+(' & ' if key=='allOf' else ' | ').join(ts(v) for v in schema[key])+')'
            rest={k:v for k,v in schema.items() if k!=key}
            return '('+ts(rest)+' & '+branches+')' if 'type' in rest or 'properties' in rest else branches
    kind=schema.get('type')
    if isinstance(kind,list):return '('+' | '.join(ts({**schema,'type':k}) for k in kind)+')'
    if kind=='object':
        props=schema.get('properties',{});required=schema.get('required',[])
        fields=[json.dumps(k)+('' if k in required else '?')+': '+ts(v) for k,v in props.items()]
        extra=schema.get('additionalProperties')
        if extra not in (None,False):fields.append('[key: string]: '+ts(extra))
        return '{ '+ '; '.join(fields)+' }'
    if kind=='array':return 'Array<'+ts(schema['items'])+'>'
    if kind in ('integer','number'):return 'number'
    if kind in ('string','boolean','null'):return kind
    raise ValueError(f'Unsupported schema: {schema}')

def generate():
    schemas=json.loads(subprocess.check_output(['cargo','run','--offline','--quiet','-p','reader-server-contracts','--bin','export_contracts'],cwd=ROOT))
    schemas.update(json.loads(subprocess.check_output(['cargo','run','--offline','--quiet','-p','reader-ai','--features','schema','--bin','export_ai_contracts'],cwd=ROOT)))
    all_types={}
    for name,schema in schemas.items():
        validate_schema(schema)
        for child,value in schema.get('$defs',{}).items():
            if child in all_types and all_types[child]!=value:raise ValueError('Conflicting definition '+child)
            all_types[child]=value
    # Root schemas carry dialect/title annotations that nested definitions omit.
    all_types.update(schemas)
    return '// Generated by tools/generate_api_contracts.py. Do not edit.\n'+''.join('export type '+name+' = '+ts(schema)+';\n' for name,schema in sorted(all_types.items()))+'\nexport type WireTypes = { '+''.join(name+': '+name+'; ' for name in sorted(schemas))+'};\nexport const wireSchemas = '+json.dumps(schemas,ensure_ascii=False,separators=(',',':'))+' as const;\n'

if __name__=='__main__':
    parser=argparse.ArgumentParser();parser.add_argument('--check',action='store_true');args=parser.parse_args()
    path=ROOT/'web/src/api/generated.ts';result=generate()
    if args.check:
        if not path.exists() or path.read_text()!=result:raise SystemExit('API contracts drifted; run python3 tools/generate_api_contracts.py')
    else:path.write_text(result)
